export const HEALTHY_SPLEEN_TEXT = `Blužnis yra pailgas organas esantis kairėju kūno pusėje. Galimos kelios blužnies padėtys – išilgai pilvo sienos, kai kaudalinis kraštas beveik siekia šlapimo pūslę arba L formos, kai blužnies kūnas lenkiasi ties skrandžiu ir kairiu inkstu. Blužnies parenchima yra homogeniška ir padengta plona hiperechoiška kapsule. Pas šunis - lyginant su kepenimis ir inksto žieve blužnis yra hiperechoiška. Pas kates – hiperechoiška kepenims, izoechoiška arba lengvai hiperechoiška inksto žievei. Blužnies kraujagyslės suformuoja „banginio uodegą“ ties blužnies vartais (hilus). Blužnies dydis vertinamas subjektyviai, dažnai pagal suapvalėjusius kraštus. Kai kuriuose šaltiniuose nurodomas normalus kačių blužnies plotis ties hilus yra iki 1cm. Blužnies užsilenkimas per pusę gali indikuoti splenomegaliją. Blužnis gali didėti dėl anestetikų poveikio.`
export const HEALTHY_SPLEEN_DESCR = `Normali katės blužnis.`

export const SPLENOMEGALY_NORMAL_TEXT = `Blužnis dažnai didėja, bet išlieka normalaus echogeniškumo dėl sedacijos su acepromazinu, diazepamu, ketaminu. Dėl kylančio spaudimo ir kraujotakos sutrikimų prie dešinės pusės širdies nepakankamumo, kepenų hipertenzijos, blužnies užsisukimo, blužnies venų trombozės. Taip pat dėl ekstramedulinės hematopoezės bei infiltruojančių neoplazijų pvz. limfoma ar mastocitoma.`
export const SPLENOMEGALY_NORMAL_DESCR = `Šuo, blužnies užsisukimas.`

export const SPLENOMEGALY_NOTNORM_TEXT = `Bičių korį ar kandžių išėstą audinį primenantis echogeniškumas dažnai būna prie blužnies limfomos. Difuzinis hipoechogeniškumas, su hiperechoiškomis trumpomis linijomis ( kolapsavusios kraujagyslės) matomas prie blužnies užsisukimo. Hipoechogeniška parenchima gali būti prie ekstramedulinės hematopoezės, gerybinės limfoidinės hiperplazijos (dėl uždegimo), infekcijos, infarktų ir infiltracinių neoplazijų. FNA rekomenduojama tikslesnei diagnozei.`
export const SPLENOMEGALY_NOTNORM_DESCR = `Šuo, limfoma.`

export const LOCAL_PARENCHYMAL_DISEASE_TEXT = `Smarkiai hiperechoiški dariniai lokalizuoti ties blužnies mezenteriniu kraštu dažnai būna gerybinės mielolipomos, randamos pas vyresnio amžiaus šunis ir kates. Hipoechoiški dariniai gali būti gerybiniai: hematomos, gerybinė mazgelinė hiperplazija (benign nodular hyperplasia) ir piktybiniai: hemangiosarkoma, kitos sarkomos, mastocitomos, histiocitomos ar metastazės.`
export const LOCAL_PARENCHYMAL_DISEASE_DESCR = `Mielolipomos, šuo.`

export const GENER_PARENCHYMAL_DISEASE_TEXT = `Auglys kylantis iš kraujagyliu endotelio. Dažnesnis pas vyresnio amžiaus, didelių veislių šunis. Predisponuoti vokiečių aviganiai, auksaspalviai retriveriai, labradorai ir šnauceriai. Iki 25% šunų su hemangiosarkoma blužnyje, diagnozės metu jau turi metastazes dešiniajame prieširdyje. Ši neoplazija taip pat linkusi metastazuoti į plaučius, inkstus, kepenis. Echoskopu hemangiosarkoma matoma kaip mišraus echogeniškumo masė. FNA mažai vertinga, nes hemangiosarkomos nelinkusios atiduoti lastelių, didelės kraujavimo bei išsėjimo rizikos. Hematomas sudaro kraujas ir fibrinas. Didelės hematomos gali suardyti kapsulę ir imti kraujuoti. Vis dėlto, kraujavimas į pilvą daug būdingesnis dėl hemangiosarkomos, nei hematomos. Hematomos gali kilti ir iš suvežėjusio audinio. Diferencijacijai būtinas histologinis tyrimas, nes abi būklės echoskopiniame tyrime gali atrodyti vienodai, o fna yra nediagnostinis.`
export const GENER_PARENCHYMAL_DISEASE_DESCR = `Šuo, hemangiosarkoma.`